// Basic Actions
export const SELECT_PROJECT = 'SELECT_PROJECT'
export const SELECT_EXPERIENCE = 'SELECT_EXPERIENCE'

// Tag Actions
export const SELECT_TAG = 'SELECT_TAG'
export const FILTER_SELECT_TAG = 'FILTER_SELECT_TAG'

/* 
	Firebase Actions 
*/

// Tags
export const FETCH_TAGS_START = 'FETCH_TAGS_START'
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS'
export const FETCH_TAGS_FAILURE = 'FETCH_TAGS_FAILURE'
export const CREATE_TAG_START = 'CREATE_TAG_START'
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS'
export const CREATE_TAG_FAILURE = 'CREATE_TAG_FAILURE'
export const EDIT_TAG_START = 'EDIT_TAG_START'
export const EDIT_TAG_SUCCESS = 'EDIT_TAG_SUCCESS'
export const EDIT_TAG_FAILURE = 'EDIT_TAG_FAILURE'
export const DELETE_TAG_START = 'DELETE_TAG_START'
export const DELETE_TAG_SUCCESS = 'DELETE_TAG_SUCCESS'
export const DELETE_TAG_FAILURE = 'DELETE_TAG_FAILURE'

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE'
export const CREATE_PROJECT_START = 'CREATE_PROJECT_START'
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE'
export const EDIT_PROJECT_START = 'EDIT_PROJECT_START'
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS'
export const EDIT_PROJECT_FAILURE = 'EDIT_PROJECT_FAILURE'
export const DELETE_PROJECT_START = 'DELETE_PROJECT_START'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE'

export const FETCH_EXPERIENCES_START = 'FETCH_EXPERIENCES_START'
export const FETCH_EXPERIENCES_SUCCESS = 'FETCH_EXPERIENCES_SUCCESS'
export const FETCH_EXPERIENCES_FAILURE = 'FETCH_EXPERIENCES_FAILURE'
export const CREATE_EXPERIENCE_START = 'CREATE_EXPERIENCE_START'
export const CREATE_EXPERIENCE_SUCCESS = 'CREATE_EXPERIENCE_SUCCESS'
export const CREATE_EXPERIENCE_FAILURE = 'CREATE_EXPERIENCE_FAILURE'
export const EDIT_EXPERIENCE_START = 'EDIT_EXPERIENCE_START'
export const EDIT_EXPERIENCE_SUCCESS = 'EDIT_EXPERIENCE_SUCCESS'
export const EDIT_EXPERIENCE_FAILURE = 'EDIT_EXPERIENCE_FAILURE'
export const DELETE_EXPERIENCE_START = 'DELETE_EXPERIENCE_START'
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS'
export const DELETE_EXPERIENCE_FAILURE = 'DELETE_EXPERIENCE_FAILURE'
